/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code.main;

/**
 *
 * @author hp
 */
public class InWorkFrame extends javax.swing.JFrame {

    /**
     * Creates new form InWorkFrame
     */
    public InWorkFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        activity = new javax.swing.JLabel();
        activity1 = new javax.swing.JLabel();
        activity2 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/main/sleepin.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 440, 310));

        title.setFont(new java.awt.Font("Myriad Hebrew", 1, 80)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Oh no!");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 280, 90));

        activity.setBackground(new java.awt.Color(255, 255, 255));
        activity.setFont(new java.awt.Font("Myriad Hebrew", 1, 36)); // NOI18N
        activity.setForeground(new java.awt.Color(255, 255, 255));
        activity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activity.setText(":(");
        getContentPane().add(activity, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 930, 50));

        activity1.setBackground(new java.awt.Color(255, 255, 255));
        activity1.setFont(new java.awt.Font("Myriad Hebrew", 1, 36)); // NOI18N
        activity1.setForeground(new java.awt.Color(255, 255, 255));
        activity1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activity1.setText("Has matado a Mudkip!");
        getContentPane().add(activity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 440, 50));

        activity2.setBackground(new java.awt.Color(255, 255, 255));
        activity2.setFont(new java.awt.Font("Myriad Hebrew", 1, 36)); // NOI18N
        activity2.setForeground(new java.awt.Color(255, 255, 255));
        activity2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activity2.setText("Habrá que esperar a que reviva para más actividades");
        getContentPane().add(activity2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 930, 50));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/main/salir.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/main/backgrounds/home.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 660));

        setSize(new java.awt.Dimension(947, 698));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        new GameSelector().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InWorkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InWorkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InWorkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InWorkFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InWorkFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activity;
    private javax.swing.JLabel activity1;
    private javax.swing.JLabel activity2;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
