/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code.grades.first.alphabet;

import code.util.Letter;
import java.awt.Color;
import static java.awt.Color.*;
import java.io.IOException;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Alphabet extends javax.swing.JFrame {
    
    private Clip sound;
    private int numLetra = 0;
    private Letter[] letters = new Letter[26];

    /**
     * Creates new form ADeAbeja
     */
    public Alphabet() {
        String[] references = {
            "Abeja","Ballena","Conejo","Dinosaurio","Elefante","Foca","Gato","Husky","Iguana",
            "Jirafa","Koala","León","Mukip","Naval","Oso","Panda","mosQuito","Ratón","Serpiente",
            "Tortuga","Unicornio","Vaca","kiWi","Xipihas","Yak","Zorro"
        };
        Color[] colors = {
            YELLOW,BLUE,CYAN,GREEN,GRAY,BLUE,ORANGE,RED,GREEN,
            ORANGE,LIGHT_GRAY,ORANGE,BLUE,BLUE,BLACK,BLACK,BLACK,
            GREEN,LIGHT_GRAY,GREEN,GREEN,PINK,BLACK,GRAY,BLUE,RED,
            ORANGE
        };
        
        int j = 0;
        for (char i = 'a'; i <= 'z'; i++) {
            letters[j] = new Letter(i, references[j], colors[j]);
            j++;
        }
        
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        play = new javax.swing.JButton();
        left = new javax.swing.JLabel();
        right = new javax.swing.JLabel();
        play1 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tahoma", 1, 56)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("A de Abeja");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 840, 60));

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/grades/first/alphabet/a.png"))); // NOI18N
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 150, 540, 370));

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 550, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 570, 390));

        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/main/nota.jpg"))); // NOI18N
        play.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        play.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        getContentPane().add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 110, 110));

        left.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/main/left.png"))); // NOI18N
        left.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        left.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftMouseClicked(evt);
            }
        });
        getContentPane().add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        right.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/main/right.png"))); // NOI18N
        right.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        right.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightMouseClicked(evt);
            }
        });
        getContentPane().add(right, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, -1, -1));

        play1.setBackground(new java.awt.Color(255, 255, 255));
        play1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/main/start.png"))); // NOI18N
        play1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        play1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(play1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 110, 110));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/main/backgrounds/bgAbecedario.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -290, -1, -1));

        setSize(new java.awt.Dimension(950, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightMouseClicked
        // TODO add your handling code here:
        numLetra++;
        if(numLetra > (letters.length - 1) ) numLetra = 0;
        
        updateLetter();
    }//GEN-LAST:event_rightMouseClicked

    private void leftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftMouseClicked
        // TODO add your handling code here:
        numLetra--;
        if(numLetra < 0) numLetra = letters.length - 1;
        
        updateLetter();
    }//GEN-LAST:event_leftMouseClicked

    public void updateLetter(){
        Letter letter = letters[numLetra];
        
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource(
                "/resources/images/grades/first/alphabet/" + letter.name + ".PNG"
        )));
        title.setText( letter.getReference() );
        title.setForeground( letter.color );
        jPanel1.setBackground( letter.color );
        
        playSound();
    }
    
    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
        playSound();
    }//GEN-LAST:event_playActionPerformed

    public void playSound(){
        playSound(letters[numLetra].getStringName(),"wav");
    }
    
    public void playSound(String soundName, String soundExt){
        try {
            sound.stop();
        } catch(Exception e){}
        
        try {
            this.sound = AudioSystem.getClip();
            
            sound.open(
                    AudioSystem.getAudioInputStream(getClass().getResourceAsStream(
                            String.format("/resources/sounds/grades/first/spanish/alphabet/%s.%s", soundName, soundExt)
                    ))
            );
            sound.start();
            Thread.sleep(100);
        } catch( IOException | InterruptedException | LineUnavailableException | UnsupportedAudioFileException e ) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alphabet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alphabet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alphabet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alphabet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alphabet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel left;
    private javax.swing.JButton play;
    private javax.swing.JButton play1;
    private javax.swing.JLabel right;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
