/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code.grades.first.spanish.FullWrite;


import code.grades.first.spanish.DragAndDrop.NameToImage;
import code.menu.Home;
import code.util.controllers.HistorialController;
import java.awt.Color;


/**
 *
 * @author admin
 */
public class Gato extends javax.swing.JFrame {

    boolean back=false;
    /**
     * Creates new form Gato
     */
    public Gato() {
        initComponents();
        setLocationRelativeTo(null);
        g.requestFocus();

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volver = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        o = new javax.swing.JTextField();
        g = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        t = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        expresion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuPrincipal = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volver.setBackground(new java.awt.Color(255, 255, 255));
        volver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        volver.setForeground(new java.awt.Color(0, 102, 102));
        volver.setText("<");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 180, 40));

        siguiente.setBackground(new java.awt.Color(255, 255, 255));
        siguiente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        siguiente.setForeground(new java.awt.Color(0, 102, 102));
        siguiente.setText(">");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        getContentPane().add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 580, 180, 40));

        o.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        o.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                oKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                oKeyReleased(evt);
            }
        });
        getContentPane().add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 70, 40));

        g.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        g.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gKeyReleased(evt);
            }
        });
        getContentPane().add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 70, 40));

        a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aKeyReleased(evt);
            }
        });
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 70, 40));

        t.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tKeyReleased(evt);
            }
        });
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 70, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/grades/first/spanish/Gatito.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 290, 250));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 310, 270));

        expresion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/expressions/expresion1.PNG"))); // NOI18N
        getContentPane().add(expresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Escribe el nombre de la imagen.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 270, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Instrucciones:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 140, -1));

        title.setFont(new java.awt.Font("Tahoma", 1, 56)); // NOI18N
        title.setForeground(new java.awt.Color(0, 204, 204));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Escribamos!");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 840, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/grades/first/spanish/backgrounds/paisaje4.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 650));

        jMenu1.setText("Menu");

        MenuPrincipal.setText("Menu Principal");
        MenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrincipalActionPerformed(evt);
            }
        });
        jMenu1.add(MenuPrincipal);

        jMenuItem1.setText("Volver");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jMenu1.add(Salir);

        menu.add(jMenu1);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void volver() {
        HistorialController.back();
    }
    
    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        volver();
    }//GEN-LAST:event_volverActionPerformed

    public void verificar(){
        String q = g.getText();
        String w = a.getText();
        String e = t.getText();
        String r = o.getText();
        String gato = q + w + e + r;
        if(gato.equalsIgnoreCase("Gato")){
            g.setForeground(Color.GREEN);
            a.setForeground(Color.GREEN);
            t.setForeground(Color.GREEN);
            o.setForeground(Color.GREEN);
            expresion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/expressions/correcto.gif")));
        } 
        else{
            g.setForeground(Color.RED);
            a.setForeground(Color.RED);
            t.setForeground(Color.RED);
            o.setForeground(Color.RED);
            expresion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/expressions/triste.gif")));
        } 
    }

    public void reiniciar(){
        expresion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/expressions/expresion1.PNG")));
        g.setForeground(Color.BLACK);
        a.setForeground(Color.BLACK);
        t.setForeground(Color.BLACK);
        o.setForeground(Color.BLACK);
        if( !("".equals(g.getText())) && !("".equals(a.getText())) && !("".equals(t.getText())) && !("".equals(o.getText()))){
            verificar();
        }
    }
    
    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        HistorialController.next(new Silla());
    }//GEN-LAST:event_siguienteActionPerformed

    private void MenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrincipalActionPerformed
        // TODO add your handling code here:
        HistorialController.nextMain();
    }//GEN-LAST:event_MenuPrincipalActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        volver();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void gKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gKeyPressed
        // TODO add your handling code here:
        if( !( "G".equalsIgnoreCase(g.getText()) && evt.getKeyChar()=='a' ) ){
            g.setText("");
        } else {
            back=true;
        }
        if( evt.getKeyChar() == 'G') {
            a.requestFocus();
        }
    }//GEN-LAST:event_gKeyPressed

    private void aKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyPressed
        // TODO add your handling code here:
        if( !( "a".equalsIgnoreCase(a.getText()) && evt.getKeyChar()=='t' ) ){
            a.setText("");
        } else {
            back=true;
        }
    }//GEN-LAST:event_aKeyPressed

    private void tKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tKeyPressed
        // TODO add your handling code here:
        if( !( "t".equalsIgnoreCase(t.getText()) && evt.getKeyChar()=='o' ) ){
            t.setText("");
        } else {
            back=true;
        }
    }//GEN-LAST:event_tKeyPressed

    private void gKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gKeyReleased
        // TODO add your handling code here:
        if( evt.getKeyChar() == 'G' || evt.getKeyChar()=='g'){
            a.requestFocus();
        }
        if( back ){
            g.setText("G");
            a.setText("a");
            t.requestFocus();
            back=false;
        }
        reiniciar();
    }//GEN-LAST:event_gKeyReleased

    private void oKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oKeyPressed
        // TODO add your handling code here:
        o.setText("");
    }//GEN-LAST:event_oKeyPressed

    private void aKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyReleased
        // TODO add your handling code here:
        if( evt.getKeyChar() == 'a'){
            t.requestFocus();
        }
        if( evt.getKeyChar()==8 ){
            g.requestFocus();
        }
        if( back ){
            a.setText("a");
            t.setText("t");
            o.requestFocus();
            back=false;
        }
        reiniciar();
    }//GEN-LAST:event_aKeyReleased

    private void tKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tKeyReleased
        // TODO add your handling code here:
        if( evt.getKeyChar()=='t' ){
            o.requestFocus();
        }
        if( evt.getKeyChar()==8 ){
            a.requestFocus();
        }
        if( back ){
            t.setText("t");
            o.setText("o");
            o.requestFocus();
            back=false;
        }
        reiniciar();
    }//GEN-LAST:event_tKeyReleased

    private void oKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oKeyReleased
        // TODO add your handling code here:
        if( evt.getKeyChar()==8 ){
            t.requestFocus();
        }
        reiniciar();
    }//GEN-LAST:event_oKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuPrincipal;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JTextField a;
    private javax.swing.JLabel background;
    private javax.swing.JLabel expresion;
    private javax.swing.JTextField g;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JTextField o;
    private javax.swing.JButton siguiente;
    private javax.swing.JTextField t;
    private javax.swing.JLabel title;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
