/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code.grades.first.spanish.FullWrite;


import code.grades.first.spanish.Finish;
import code.main.Home;
import java.awt.Color;

/**
 *
 * @author admin
 */
public class Silla extends javax.swing.JFrame {

    boolean back=false;
    /**
     * Creates new form Finish
     */
    public Silla() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volver = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        a = new javax.swing.JTextField();
        s = new javax.swing.JTextField();
        i = new javax.swing.JTextField();
        l = new javax.swing.JTextField();
        L = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        expresion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuPrincipal = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volver.setBackground(new java.awt.Color(255, 255, 255));
        volver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        volver.setForeground(new java.awt.Color(0, 102, 102));
        volver.setText("<");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 170, 40));

        siguiente.setBackground(new java.awt.Color(255, 255, 255));
        siguiente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        siguiente.setForeground(new java.awt.Color(0, 102, 102));
        siguiente.setText(">");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        getContentPane().add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, 170, 40));

        a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aKeyReleased(evt);
            }
        });
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 70, 40));

        s.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sKeyReleased(evt);
            }
        });
        getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 70, 40));

        i.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        i.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                iKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                iKeyReleased(evt);
            }
        });
        getContentPane().add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 70, 40));

        l.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        l.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lKeyReleased(evt);
            }
        });
        getContentPane().add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 70, 40));

        L.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        L.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LKeyReleased(evt);
            }
        });
        getContentPane().add(L, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 70, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/grades/first/spanish/Silla.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 290, 250));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 310, 270));

        expresion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/expressions/expresion1.PNG"))); // NOI18N
        getContentPane().add(expresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Escribe el nombre de la imagen.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 270, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Instrucciones:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 140, -1));

        title.setFont(new java.awt.Font("Tahoma", 1, 56)); // NOI18N
        title.setForeground(new java.awt.Color(0, 204, 204));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Escribamos!");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 840, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/grades/first/spanish/backgrounds/paisaje4.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 650));

        jMenu1.setText("Menu");

        MenuPrincipal.setText("Menu Principal");
        MenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrincipalActionPerformed(evt);
            }
        });
        jMenu1.add(MenuPrincipal);

        jMenuItem1.setText("Volver");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jMenu1.add(Salir);

        menu.add(jMenu1);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void volver(){
        new Gato().setVisible(true);
        this.dispose();
    }
    
    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        volver();
    }//GEN-LAST:event_volverActionPerformed

    public void verificar(){
        String q = s.getText();
        String w = i.getText();
        String r = l.getText();
        String t = L.getText();
        String y = a.getText();
        String silla = q + w + r + t + y;
        if(silla.equalsIgnoreCase("Silla")){
            s.setForeground(Color.GREEN);
            i.setForeground(Color.GREEN);
            l.setForeground(Color.GREEN);
            L.setForeground(Color.GREEN);
            a.setForeground(Color.GREEN);
            expresion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/expressions/correcto.gif")));
        }
        else{
            s.setForeground(Color.RED);
            i.setForeground(Color.RED);
            l.setForeground(Color.RED);
            L.setForeground(Color.RED);
            a.setForeground(Color.RED);
            expresion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/expressions/triste.gif")));
        }
    }
    
    public void reiniciar(){
        expresion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/expressions/expresion1.PNG")));
        s.setForeground(Color.BLACK);
        i.setForeground(Color.BLACK);
        l.setForeground(Color.BLACK);
        L.setForeground(Color.BLACK);
        a.setForeground(Color.BLACK);
        if( !("".equals(s.getText()))  &&  !("".equals(i.getText()))  && !("".equals(l.getText())) &&  !("".equals(L.getText()))  &&  !("".equals(a.getText()))){
            verificar();
        }
    }
    
    private void MenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrincipalActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuPrincipalActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new Silla().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void sKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sKeyPressed
        // TODO add your handling code here:
        if( !( "s".equalsIgnoreCase(s.getText()) && evt.getKeyChar()=='i' ) ){
           s.setText(""); 
        } else {
            back=true;
        }
    }//GEN-LAST:event_sKeyPressed

    private void iKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iKeyPressed
        // TODO add your handling code here:
        if( !( "i".equalsIgnoreCase(i.getText()) && evt.getKeyChar()=='l' ) ){
            i.setText("");
        } else {
            back=true;
        }
    }//GEN-LAST:event_iKeyPressed

    private void lKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lKeyPressed
        // TODO add your handling code here:
        if( !( "l".equalsIgnoreCase(l.getText()) && evt.getKeyChar()=='l' ) ){
            l.setText("");
        } else {
            back=true;
        }
    }//GEN-LAST:event_lKeyPressed

    private void LKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LKeyPressed
        // TODO add your handling code here:
        if( !( "l".equalsIgnoreCase(L.getText()) && evt.getKeyChar()=='a' ) ){
            L.setText("");
        } else {
            back=true;
        }
    }//GEN-LAST:event_LKeyPressed

    private void sKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sKeyReleased
        // TODO add your handling code here:
        if( evt.getKeyChar() == 'S' || evt.getKeyChar()=='s'){
            i.requestFocus();
        }
        if( back ){
            s.setText("S");
            i.setText("i");
            l.requestFocus();
            back=false;
        }
        reiniciar();
    }//GEN-LAST:event_sKeyReleased

    private void aKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyPressed
        // TODO add your handling code here:
        a.setText("");
    }//GEN-LAST:event_aKeyPressed

    private void iKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iKeyReleased
        // TODO add your handling code here:
        if( evt.getKeyChar() == 'i'){
            l.requestFocus();
        }
        if( evt.getKeyChar()==8){
            s.requestFocus();
        }
        if( back ){
            i.setText("i");
            l.setText("l");
            L.requestFocus();
            back=false;
        }
        reiniciar();
    }//GEN-LAST:event_iKeyReleased

    private void lKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyChar() == 'l'){
            L.requestFocus();
        }
        if( evt.getKeyChar()==8){
            i.requestFocus();
        }
        if( back ){
            l.setText("l");
            L.setText("l");
            a.requestFocus();
            back=false;
        }
        reiniciar();
    }//GEN-LAST:event_lKeyReleased

    private void aKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyReleased
        // TODO add your handling code here:
        if( evt.getKeyChar()==8){
            L.requestFocus();
        }
        reiniciar();
    }//GEN-LAST:event_aKeyReleased

    private void LKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LKeyReleased
        // TODO add your handling code here:
        if( evt.getKeyChar() == 'l'){
            a.requestFocus();
        }
        if( evt.getKeyChar()==8){
            l.requestFocus();
        }
        if( back ){
            L.setText("l");
            a.setText("a");
            a.requestFocus();
            back=false;
        }
        reiniciar();
    }//GEN-LAST:event_LKeyReleased

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        new Finish().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_siguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finish().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField L;
    private javax.swing.JMenuItem MenuPrincipal;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JTextField a;
    private javax.swing.JLabel background;
    private javax.swing.JLabel expresion;
    private javax.swing.JTextField i;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField l;
    private javax.swing.JMenuBar menu;
    private javax.swing.JTextField s;
    private javax.swing.JButton siguiente;
    private javax.swing.JLabel title;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
