/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code.grades.first;

import code.main.InWorkFrame;
import code.grades.first.spanish.Write.Mariposa;
import code.main.Home;
import javax.sound.sampled.Clip;

/**
 *
 * @author hp
 */
public class GameSelector extends javax.swing.JFrame {
    
    private Clip sound;
    // Game counter
    private int act = 0;
    // Games list
    Activity[] activities = {
        new Activity("Escritura", "ABC", new Mariposa()),
        new Activity("Matemáticas", "matematicas", new InWorkFrame()),
        new Activity("Cuentos", new InWorkFrame()),
        new Activity("Abecedario", new InWorkFrame()),
        new Activity("Números", "numeros", new InWorkFrame())
    };
    
    // Game Class (helper)
    public class Activity {
        public String name;
        public String image;
        public javax.swing.JFrame frame;
        
        public Activity(String name, String image, javax.swing.JFrame frame){
            this.name = name;
            this.image = image;
            this.frame = frame;
        }
        
        public Activity(String name, javax.swing.JFrame frame){
            this.name = name;
            this.image = name.toLowerCase();
            this.frame = frame;
        }
    }
    /**
     * Creates new form GameSelector
     */
    public GameSelector() {
        initComponents();
    }
    
    public GameSelector(Clip sound){
        this.sound = sound;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        left = new javax.swing.JLabel();
        right = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        activity = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/main/left.png"))); // NOI18N
        left.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        left.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftMouseClicked(evt);
            }
        });
        getContentPane().add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        right.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/main/right.png"))); // NOI18N
        right.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        right.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightMouseClicked(evt);
            }
        });
        getContentPane().add(right, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/main/salir.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        title.setFont(new java.awt.Font("Myriad Hebrew", 1, 80)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Actividades");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 450, 90));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        activity.setBackground(new java.awt.Color(255, 255, 255));
        activity.setFont(new java.awt.Font("Myriad Hebrew", 1, 48)); // NOI18N
        activity.setForeground(new java.awt.Color(0, 204, 204));
        activity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activity.setText("Escritura");
        jPanel4.add(activity, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 440, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 440, 70));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 460, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/GameSelector/ABC.png"))); // NOI18N
        imagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagenMouseClicked(evt);
            }
        });
        jPanel1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 330, 320));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 350, 340));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/main/backgrounds/bgActividadesPrimero.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1320, 680));

        setSize(new java.awt.Dimension(950, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void imagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenMouseClicked
        // TODO add your handling code here:
        sound.stop();
        activities[act].frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_imagenMouseClicked
        
    private void rightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightMouseClicked
        // TODO add your handling code here:
        act++;
        if(act > (activities.length-1) ) act = 0;
        
        updateActivity();
    }//GEN-LAST:event_rightMouseClicked

    private void leftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftMouseClicked
        // TODO add your handling code here:
        act--;
        if(act < 0) act = activities.length-1;
        
        updateActivity();
    }//GEN-LAST:event_leftMouseClicked

    private void updateActivity(){
        Activity actualActivity = activities[act];
        
        activity.setText(actualActivity.name);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/GameSelector/" + actualActivity.image + ".PNG")));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameSelector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activity;
    private javax.swing.JLabel back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel left;
    private javax.swing.JLabel right;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
